### ISSUE TITLE
Shape of variable hidden weights_0 doesn't match with the shape of tensor 

### ISSUE THREAD

**Issue by RuyuanWan** [HKUST-KnowComp/Exo-PCR#1]
Hi,
I am trying to reproduce your code but got an error:

```
File "./tensorflow/python/training/checkpoint_utils.py", line 229, in _init_from_checkpoint
    tensor_name_in_ckpt, str(variable_map[tensor_name_in_ckpt])

ValueError: Shape of variable coref_layer/slow_antecedent_scores/hidden_weights_0:0 ((7012, 3000)) doesn't match with shape of tensor coref_layer/slow_antecedent_scores/hidden_weights_0 ([7052, 3000]) from checkpoint reader.

```

**Comment by YuCosine** [comment]
Hi,

I have updated README and the code to enable reproduction of "evaluation only" and "training from scratch." Please download the trained models following the instructions and run the code again.

**Comment by RuyuanWan** [comment]
Hi, 

Your links of video, slides and poster in the readme are not available to access the file now. Would you mind sharing the accessible link to those materials? 

Thanks!

**Comment by YuCosine** [comment]
@RuyuanWan 
Hi,
I have tested the links and they are accessible. Maybe you can check your accessibility to google drive.

**Comment by RuyuanWan** [comment]
@YuCosine Thanks for your quick response! I have successfully opened them now.
