### ISSUE TITLE
Type error in Similarity 

### ISSUE THREAD

**Issue by RuyuanWan** [HKUST-KnowComp/Exo-PCR#2]
Hi,

When I trained bert_base model with the train.py, it gave me such error after "Loaded 500 eval examples":

Traceback (most recent call last):
  File "train.py", line 93, in <module>
    eval_summary, eval_f1 = model.evaluate(session, tf_global_step)
  File "/Exo-PCR/independent.py", line 738, in evaluate
    coref_predictions[example["doc_key"]] = self.evaluate_coref(top_span_starts, top_span_ends, predicted_antecedents, gold_clusters, coref_evaluator)
  File "/Exo-PCR/independent.py", line 696, in evaluate_coref
    evaluator.update(predicted_clusters, gold_clusters, mention_to_predicted, mention_to_gold)
  File "/Exo-PCR/metrics.py", line 23, in update
    e.update(predicted, gold, mention_to_predicted, mention_to_gold)
  File "/Exo-PCR/metrics.py", line 48, in update
    pn, pd, rn, rd = self.metric(predicted, gold)
  File "/Exo-PCR/metrics.py", line 128, in ceafe
    similarity = sum(scores[matching[:, 0], matching[:, 1]])
TypeError: tuple indices must be integers or slices, not tuple

The logs look fine in TensorBoard. Have you encountered a similar error on your end? Could you please help me take a look what may cause the error?

Thanks!

**Comment by YuCosine** [comment]
Hi,
I do not have such an error on my system. I guess it is due to the version of scikit-learn. You can try install scikit_learn==0.23.1 as in the `requirements.txt`.

**Comment by YuCosine** [comment]
Hi,
I do not have such an error on my system. I guess it is due to the version of scikit-learn. You can try installing scikit_learn==0.23.1 as in the requirements.txt.

**Comment by RuyuanWan** [comment]
Hi,

Thanks for the quick response! When I got the error, I was using scikit_learn==0.23.1.
But I figured it out later, this is what I changed:
**Original code running into error**: similarity = sum(scores[matching[:, 0], matching[:, 1]]) 
**Change that fixes the error**: similarity = sum(scores[np.array(matching)[:][0], np.array(matching)[:][1]])
