### ISSUE TITLE
Could it be used on any dataset?

### ISSUE THREAD

**Issue by MayarOssama** [HKUST-KnowComp/Exo-PCR#3]
Hello, thanks for sharing your great work.
Could this approach be used in an end-to-end manner or a different dataset?

Thanks in advance

**Comment by YuCosine** [comment]
Hi,

this approach can be used in an end-to-end manner on VisPro dataset following the instructions in README.

To use it on a different dataset, you need to provide the data in the same format as [`data/test.vispro.pool.1.1.bert.512.jsonlines`](https://github.com/HKUST-KnowComp/Exo-PCR/blob/main/data/test.vispro.pool.1.1.bert.512.jsonlines), which is used by the [`tensorize_example`](https://github.com/HKUST-KnowComp/Exo-PCR/blob/03f0dc2f2e20580e8f791278ccbbdea5aefd95df/independent.py#L180) function. The information needed are:

+ `doc_key`: the dialogue key starts with "dl".
+ `sentences`: dialogue tokens tokenized by a BERT tokenizer.
+ `speakers`: speakers of each token.
+ `clusters`: the gt coreference clusters, in which words in dialogues are recorded as a `list`, and objects in the out-of-text object pools are recorded as a `dict`.
+ `pronoun_info`: information of pronouns, including `current_pronoun` (the position of the target pronoun), `candidate_NPs` (the positions of candidate noun phrases in dialogues), `correct_NPs` (the positions of correct referents, including words in dialogues and out-of-text objects), and `reference_type` (0 for referential pronouns).
